FROM golang:1.24.6-bullseye

ENV TZ="Asia/Tokyo"
ADD ./bff /go/src/app
WORKDIR /go/src/app

RUN --mount=type=cache,target=/go/pkg/mod/ \
    go mod download

RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/air-verse/air@v1.60.0
