FROM golang:1.23-bullseye

ENV TZ="Asia/Tokyo"
ADD ./bff /go/src/app
WORKDIR /go/src/app

RUN --mount=type=cache,target=/go/pkg/mod/ \
    go mod download

RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/air-verse/air@latest
