// Code generated by MockGen. DO NOT EDIT.
// Source: backend/domain/repository (interfaces: SubTaskRepository)

// Package mock is a generated GoMock package.
package mock

import (
	model "backend/domain/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSubTaskRepository is a mock of SubTaskRepository interface.
type MockSubTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubTaskRepositoryMockRecorder
}

// MockSubTaskRepositoryMockRecorder is the mock recorder for MockSubTaskRepository.
type MockSubTaskRepositoryMockRecorder struct {
	mock *MockSubTaskRepository
}

// NewMockSubTaskRepository creates a new mock instance.
func NewMockSubTaskRepository(ctrl *gomock.Controller) *MockSubTaskRepository {
	mock := &MockSubTaskRepository{ctrl: ctrl}
	mock.recorder = &MockSubTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubTaskRepository) EXPECT() *MockSubTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubTaskRepository) Create(arg0 context.Context, arg1 model.SubTask) (*model.SubTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.SubTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubTaskRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubTaskRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockSubTaskRepository) FindByID(arg0 context.Context, arg1 uint64) (*model.SubTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.SubTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSubTaskRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSubTaskRepository)(nil).FindByID), arg0, arg1)
}

// ListByTaskID mocks base method.
func (m *MockSubTaskRepository) ListByTaskID(arg0 context.Context, arg1 uint64) ([]model.SubTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTaskID", arg0, arg1)
	ret0, _ := ret[0].([]model.SubTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTaskID indicates an expected call of ListByTaskID.
func (mr *MockSubTaskRepositoryMockRecorder) ListByTaskID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTaskID", reflect.TypeOf((*MockSubTaskRepository)(nil).ListByTaskID), arg0, arg1)
}

// Update mocks base method.
func (m *MockSubTaskRepository) Update(arg0 context.Context, arg1 model.SubTask) (*model.SubTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*model.SubTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSubTaskRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubTaskRepository)(nil).Update), arg0, arg1)
}
