package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/naoyakurokawa/go_grpc_graphql/domain/model"
	"github.com/naoyakurokawa/go_grpc_graphql/middleware/session"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (bool, error) {
	userID, err := r.AuthController.Login(ctx, email, password)
	if err != nil {
		return false, err
	}

	sessionID := r.SessionManager.CreateSession(userID)
	if err := session.SetSessionCookie(ctx, sessionID); err != nil {
		return false, err
	}

	return true, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	sessionID, ok := session.SessionIDFromContext(ctx)
	if ok {
		r.SessionManager.DeleteSession(sessionID)
	}

	if err := session.ClearSessionCookie(ctx); err != nil {
		return false, err
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := session.UserIDFromContext(ctx)
	if !ok {
		return nil, nil
	}

	user, err := r.AuthController.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	return user, nil
}
