package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"strings"

	"github.com/naoyakurokawa/go_grpc_graphql/domain/model"
	"github.com/naoyakurokawa/go_grpc_graphql/domain/repository"
	"github.com/naoyakurokawa/go_grpc_graphql/graph"
	"github.com/naoyakurokawa/go_grpc_graphql/middleware/session"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.NewTask) (*model.Task, error) {
	if _, err := requireUserID(ctx); err != nil {
		return nil, err
	}
	return r.TodoController.CreateTask(ctx, input)
}

// CreateSubTask is the resolver for the createSubTask field.
func (r *mutationResolver) CreateSubTask(ctx context.Context, input model.NewSubTask) (*model.SubTask, error) {
	if _, err := requireUserID(ctx); err != nil {
		return nil, err
	}
	return r.TodoController.CreateSubTask(ctx, input)
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, input model.UpdateTask) (*model.Task, error) {
	if _, err := requireUserID(ctx); err != nil {
		return nil, err
	}
	return r.TodoController.UpdateTask(ctx, input)
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id uint64) (bool, error) {
	if _, err := requireUserID(ctx); err != nil {
		return false, err
	}
	return r.TodoController.DeleteTask(ctx, id)
}

// ToggleSubTask is the resolver for the toggleSubTask field.
func (r *mutationResolver) ToggleSubTask(ctx context.Context, id uint64, completed bool) (*model.SubTask, error) {
	if _, err := requireUserID(ctx); err != nil {
		return nil, err
	}
	return r.TodoController.ToggleSubTask(ctx, id, completed)
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, categoryID *uint64, dueDateStart *string, dueDateEnd *string, incompleteOnly *bool) ([]*model.Task, error) {
	filter := repository.TaskFilter{
		CategoryID:     categoryID,
		DueDateStart:   normalizeDateArg(dueDateStart),
		DueDateEnd:     normalizeDateArg(dueDateEnd),
		IncompleteOnly: incompleteOnly,
	}
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	filter.UserID = &userID
	return r.TodoController.ListTasks(ctx, filter)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func normalizeDateArg(value *string) *string {
	if value == nil {
		return nil
	}
	trimmed := strings.TrimSpace(*value)
	if trimmed == "" {
		return nil
	}
	return &trimmed
}

func requireUserID(ctx context.Context) (uint64, error) {
	userID, ok := session.UserIDFromContext(ctx)
	if !ok {
		return 0, errors.New("unauthenticated")
	}
	return userID, nil
}
