-- +goose Up
CREATE TABLE tasks (
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(255) DEFAULT NULL,
   note TEXT DEFAULT NULL,
   completed TINYINT DEFAULT 0,
   created_at TIMESTAMP NULL DEFAULT NULL,
   updated_at TIMESTAMP NULL DEFAULT NULL
);

-- +goose Down
DROP TABLE tasks;
