// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type NewSubTask struct {
	TaskID  uint64  `json:"task_id"`
	Title   string  `json:"title"`
	Note    *string `json:"note,omitempty"`
	DueDate *string `json:"due_date,omitempty"`
}

type NewTask struct {
	Title      string  `json:"title"`
	Note       string  `json:"note"`
	CategoryID uint64  `json:"category_id"`
	DueDate    *string `json:"due_date,omitempty"`
}

type Query struct {
}

type SubTask struct {
	ID          uint64  `json:"id"`
	TaskID      uint64  `json:"task_id"`
	Title       string  `json:"title"`
	Note        string  `json:"note"`
	Completed   int32   `json:"completed"`
	CompletedAt *string `json:"completed_at,omitempty"`
	DueDate     *string `json:"due_date,omitempty"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type Task struct {
	ID          uint64     `json:"id"`
	Title       string     `json:"title"`
	Note        string     `json:"note"`
	CategoryID  *uint64    `json:"category_id,omitempty"`
	DueDate     *string    `json:"due_date,omitempty"`
	Completed   int32      `json:"completed"`
	CompletedAt *string    `json:"completed_at,omitempty"`
	CreatedAt   string     `json:"created_at"`
	UpdatedAt   string     `json:"updated_at"`
	SubTasks    []*SubTask `json:"sub_tasks"`
}

type UpdateTask struct {
	ID         uint64  `json:"id"`
	Title      *string `json:"title,omitempty"`
	Note       *string `json:"note,omitempty"`
	CategoryID *uint64 `json:"category_id,omitempty"`
	DueDate    *string `json:"due_date,omitempty"`
	Completed  *int32  `json:"completed,omitempty"`
}

type User struct {
	ID        uint64 `json:"id"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
