// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTask struct {
	Title string `json:"title"`
	Note  string `json:"note"`
}

type Query struct {
}

type Task struct {
	ID        uint64 `json:"id"`
	Title     string `json:"title"`
	Note      string `json:"note"`
	Completed int32  `json:"completed"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UpdateTask struct {
	ID        uint64  `json:"id"`
	Title     *string `json:"title,omitempty"`
	Note      *string `json:"note,omitempty"`
	Completed *int32  `json:"completed,omitempty"`
}
