// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type NewTask struct {
	Title      string  `json:"title"`
	Note       string  `json:"note"`
	CategoryID uint64  `json:"category_id"`
	DueDate    *string `json:"due_date,omitempty"`
}

type Query struct {
}

type Task struct {
	ID          uint64  `json:"id"`
	Title       string  `json:"title"`
	Note        string  `json:"note"`
	CategoryID  *uint64 `json:"category_id,omitempty"`
	DueDate     *string `json:"due_date,omitempty"`
	Completed   int32   `json:"completed"`
	CompletedAt *string `json:"completed_at,omitempty"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type UpdateTask struct {
	ID         uint64  `json:"id"`
	Title      *string `json:"title,omitempty"`
	Note       *string `json:"note,omitempty"`
	CategoryID *uint64 `json:"category_id,omitempty"`
	DueDate    *string `json:"due_date,omitempty"`
	Completed  *int32  `json:"completed,omitempty"`
}
